name: Build and Deploy Profile Site

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - uses: pnpm/action-setup@v2
      #   with:
      #     version: 7

      - uses: actions/setup-node@v3
      
      - name: Build
        env:
          REACT_APP_FLICKR_API_KEY: ${{secrets.FLICKR_API_KEY}}
          REACT_APP_FLICKR_PHOTOSETS_ID: ${{secrets.FLICKR_PHOTOSETS_ID}}
          REACT_APP_FLICKR_USER_ID: ${{secrets.FLICKR_USER_ID}}
        run: |
          npm i
          npm run build

