name: Build and Deploy Profile Site

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.28.0
      
      - name: Build profile page
        env:
          REACT_APP_FLICKR_API_KEY: ${{secrets.FLICKR_API_KEY}}
          REACT_APP_FLICKR_PHOTOSETS_ID: ${{secrets.FLICKR_PHOTOSETS_ID}}
          REACT_APP_FLICKR_USER_ID: ${{secrets.FLICKR_USER_ID}}
        run: |
          cd profile && pnpm i && CI=false pnpm build && cd ..

      - name: Move profile to correct location
        run: |
          rm -rf public && mkdir public
          mv profile/dist/* public

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
