name: Build and Deploy Profile Site

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish:   # disable for now
    if: ${{ false }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7
      
      - name: Build
        env:
          REACT_APP_FLICKR_API_KEY: ${{secrets.FLICKR_API_KEY}}
          REACT_APP_FLICKR_PHOTOSETS_ID: ${{secrets.FLICKR_PHOTOSETS_ID}}
          REACT_APP_FLICKR_USER_ID: ${{secrets.FLICKR_USER_ID}}
        run: |
          pnpm i
          # Download nord theme
          pnpm download-prismjs-theme
          pnpm build

      - name: Move favicon, and 404 page to correct location
        run: |
          mv favicon.ico dist
          mv 404.html dist

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
